import { Footer } from '@/Layout/Footer'
import Navbar from '@/Layout/Navbar'
import { ClientProviders } from '@/lib/ClientProviders'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="en">
            <body className="relative overflow-x-hidden">
                <Navbar />
                <ClientProviders>{children}</ClientProviders>
                <Footer />
            </body>
        </html>
    )
}
