import { Footer } from '@/Layout/Footer'
import Navbar from '@/Layout/Navbar'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="en">
            <Navbar />
            <body className="relative overflow-x-hidden px-8 pt-24">
                {children}
            </body>
            <Footer />
        </html>
    )
}
